"""add is_manual_created to document_segment

Revision ID: 00ba1b154193
Revises: 0ab65e1cc7fa
Create Date: 2025-07-10 14:46:00.000000

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00ba1b154193'
down_revision = '0ab65e1cc7fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加 is_manual_created 布尔字段
    with op.batch_alter_table('document_segments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_manual_created', sa.Boolean(), nullable=True, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除 is_manual_created 字段
    with op.batch_alter_table('document_segments', schema=None) as batch_op:
        batch_op.drop_column('is_manual_created')
    # ### end Alembic commands ###
