"""add source_type to document_segment

Revision ID: 5003d21b8a55
Revises: 0ab65e1cc7fa
Create Date: 2025-07-09 11:17:16.036108

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5003d21b8a55'
down_revision = '0ab65e1cc7fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 只添加 source_type 字段到 document_segments 表
    with op.batch_alter_table('document_segments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 移除 source_type 字段
    with op.batch_alter_table('document_segments', schema=None) as batch_op:
        batch_op.drop_column('source_type')
    # ### end Alembic commands ###
